# -*- coding: utf-8 -*-
"""Movie Recommendation System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eArPw4yNHWpBEAs73vsVSD_-hIf_GxmS
"""

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

print(movies.head())
print(ratings.head())

data = pd.merge(ratings, movies, left_on='movieId', right_on='movieId')
print(data.head())

user_movie_matrix = data.pivot_table(
    index='userId',
    columns='title',
    values='rating'
).fillna(0)

user_movie_matrix.head()

user_similarity = cosine_similarity(user_movie_matrix)
user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_movie_matrix.index,
    columns=user_movie_matrix.index
)

user_similarity_df.head()

def recommend_movies(user_id, num_recommendations=5):
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:]

    # Filter user_movie_matrix to align with the similar_users indices
    aligned_user_movie_matrix = user_movie_matrix.loc[similar_users.index]

    weighted_scores = np.dot(
        similar_users.values, # Convert Series to numpy array for dot product
        aligned_user_movie_matrix.values # Convert DataFrame to numpy array for dot product
    ) / similar_users.sum()

    recommendations = pd.Series(
        weighted_scores,
        index=user_movie_matrix.columns
    )

    watched_movies = user_movie_matrix.loc[user_id]
    recommendations = recommendations[watched_movies == 0]

    return recommendations.sort_values(ascending=False).head(num_recommendations)

user_id = 3
print("Recommended Movies:")
print(recommend_movies(user_id))